name: react cd

on:
  push:
    branches:
      - main

#docker image 생성해서 docker hub에 올리기
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      #깃허브 저장소에 있는 코드를 깃허브 깃허브 액션 실행 서버로 가져오기 (코드내려받기)
      - name: checkout code
        uses: actions/checkout@v4
      
      ###캐싱을 위해 필수적인 buildx 도구 설치
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #도커허브에 로그인
      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: rmsckd1640
          password: ${{ secrets.DOCKER_PASSWORD }}

      ###빌드전에 배포 설정 파일 생성하기###
      #상대경로설정이라 딱히 시크릿 설정은 안함요
      - name: create .env.production
        run: |
          #경로상에 임시로 파일 만들고 이미지 만들꺼임요 + api 요청 명시
          echo "VITE_API_BASE_URL=/api" > ./react/.env.production
      
      #빌드할 소스 위치, 이미지 생성 파일(Dockerfile), 빌드 끝나면 업로드, 이미지에 이름 달기
      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: ./react
          file: ./react/Dockerfile
          push: true
          tags: rmsckd1640/the-labot-frontend:latest

          ### 빌드하고 푸시했으면 캐시 저장소 사용 설정 해야지
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  #이제 EC2갈거임
  deploy:
    #이 이름의 단계(앞단계)가 끝나야 실행
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      #왜 또 코드 받냐? --> 소스코드는 필요없지만 docker-compose.yml 때문에
      - name: checkout code
        uses: actions/checkout@v4
      
      #docker-compose.yml파일 ec2로 전송하기 (scp)
      - name: copy docker compose to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "react/docker-compose.yml"
          target: "/home/ubuntu/the-labot-frontend"
          strip_components: 1  #맨앞에 하나 벗겨라 -> react 벗기고 파일만 경로에 전송
          
      #EC2에서 명령어 실행
      - name: deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          # 주문서에 없는 옛날 컨테이너 삭제 --remove-orphans
          # 쓰지 않는 찌꺼기 이미지들 삭제 prune (-f는 강제)
          script: |
            cd /home/ubuntu/the-labot-frontend
            docker pull rmsckd1640/the-labot-frontend:latest
            docker compose up -d --remove-orphans
            docker image prune -f
